from aoc.year2025 import day07


EXAMPLE_INPUT = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


def test_parse_example():
    data = day07.parse(EXAMPLE_INPUT)
    # TODO: adjust expected structure
    assert isinstance(data, (list, tuple, str))


def test_part1_example():
    result = day07.solve_part1(EXAMPLE_INPUT)
    assert result == 21


def test_part2_example():
    result = day07.solve_part2(EXAMPLE_INPUT)
    assert result == 40
